Add types for the new storages in 4.2
typeddjango/django-stubs pull request #1488
Opened 2023-05-10 23:45 UTC by Alexerson

Hello :wave: ,

this PR is adding types for the new storages concepts added in 4.2:
https://docs.djangoproject.com/en/4.2/ref/files/storage/#django.core.files.storage.storages
&
https://docs.djangoproject.com/en/4.2/ref/files/storage/#the-inmemorystorage-class

I didn’t find any tests for the existing storages concepts so didn’t add any. Let me know if you’d like for me to add some.

2023-05-15 20:00 UTC, intgr requested changes
Thanks! A few more tweaks :)

2023-05-15 20:00 UTC, intgr commented on django-stubs/core/files/storage.pyi
> +    def __init__(self) -> None: ...
Looks like `StorageHandler.__init__` takes an optional `backends` argument

```suggestion
    def __init__(self, backends: dict[str, Storage] | None = ...) -> None: ...
```

2023-05-15 20:00 UTC, intgr commented on django-stubs/core/files/storage.pyi
> +    def backends(self) -> dict[str, Any]: ...
Looks like dict values are `Storage` instances?

```suggestion
    def backends(self) -> dict[str, Storage]: ...
```

2023-05-15 20:00 UTC, intgr commented on django-stubs/core/files/storage.pyi
> +class StorageHandler:
AFAIK the `.pyi` file structure should exactly mirror `.py` file structure. So `StorageHandler` this should be defined in `.../files/storage/handler.pyi` and re-exported in `.../files/storage/__init__.pyi`

This requires some refactoring though, turning `storage.pyi` file into a package.

2023-05-16 04:50 UTC, Alexerson commented on django-stubs/core/files/storage.pyi
> +class StorageHandler:
Makes sense. I wasn't sure if a small diff was better or not in this case, but as it was pretty heavily refactored upstream, it makes sense to refactoring it here as well.
 I will look into this PR again hopefully by the end of the week. If not, mid next week.

2023-05-16 16:28 UTC, intgr commented on django-stubs/core/files/storage.pyi
> +class StorageHandler:
👍 I think this is already an improvement, I'm going to merge this along with my tweaks and I hope to see the follow-up PR later.

2023-05-16 16:33 UTC, intgr approved these changes
Let's merge this and fix the remaining things in a follow-up pull request.

2023-05-22 16:54 UTC, Alexerson commented
Ok, so it wasn’t actually so difficult to do that properly, and as this PR is not merged yet, I think we should do it properly right away.

The only part I wasn’t sure about was the typing of `mixins.StorageSettingsMixin`’s methods.

2023-05-26 18:51 UTC, intgr commented
> this PR is not merged yet

Oops, sorry, I was waiting for CI and forgot to merge afterwards.

2023-05-26 18:52 UTC, intgr commented on django-stubs/core/files/storage/mixins.pyi
> +        **kwargs
```suggestion
        **kwargs: Any
```

2023-05-26 19:04 UTC, Alexerson commented
No worries. The CI seems to be green again after your commit, thanks.

2023-05-26 19:05 UTC, merged