add a stub for RedirectURLMixin
typeddjango/django-stubs pull request #1641
Opened 2023-08-03 14:16 UTC by si14

# Simple stub for `contrib.auth.views.RedirectURLMixin`

I noticed that it was in the todolist and I needed it, so here it is.

2023-08-03 20:08 UTC, intgr commented on django-stubs/contrib/auth/views.pyi
>  class SuccessURLAllowedHostsMixin:
Some more changes look warranted...

`SuccessURLAllowedHostsMixin` no longer exists in Django 4.2, `LoginView` and `LogoutView` should inherit from `RedirectURLMixin` instead.

2023-08-09 12:59 UTC, intgr requested changes
Please remove `SuccessURLAllowedHostsMixin` and replace it with the new `RedirectURLMixin`.

2023-08-23 15:08 UTC, si14 commented
@intgr fixed, all tests are green

2023-08-23 15:12 UTC, intgr approved these changes
Thank you!

2023-08-23 15:13 UTC, merged