Change `BaseExpression.output_field` from `@property` to `@cached_property`
typeddjango/django-stubs pull request #1769
Opened 2023-10-13 12:34 UTC by UnknownPlatypus

Followup to #1761 and #1768.

Should also fix #1765 since the `output_field` type on `BaseExpression` is now accurate. 

This removes 6 entries from the todolist

2023-10-13 13:55 UTC, intgr commented on django-stubs/contrib/gis/db/models/functions.pyi
> +from utils.functional import cached_property
I'm surprised this passed CI, shouldn't this be:

```suggestion
from django.utils.functional import cached_property
```

2023-10-13 18:11 UTC, UnknownPlatypus commented on django-stubs/contrib/gis/db/models/functions.pyi
> +from utils.functional import cached_property
absolutely, I wonder why pycharm added the import like this, I didn't really paid attention

2023-10-25 12:05 UTC, UnknownPlatypus commented
This is unblocked by #1771 too I think

2023-11-09 12:22 UTC, intgr requested changes
Thanks! A few omissions I noticed:

* `django.contrib.gis.db.models.functions.GeomOutputGeoFunc`, `Area` attribute `output_field` can be `cached_property` too.
* `django.contrib.gis.db.backends.postgis.operations.ST_Polygon`

2023-11-10 10:02 UTC, UnknownPlatypus commented
Thanks, nice catch. I did some more greping and I think it's good now

2023-11-10 10:08 UTC, intgr approved these changes
Awesome, thanks!

2023-11-10 10:11 UTC, merged