Make as_manager method use proper generic
typeddjango/django-stubs pull request #327
Opened 2020-02-13 16:21 UTC by silviogutierrez

- Closes #324

2020-02-14 11:12 UTC, sobolevn requested changes
Thanks a lot for the fix!

2020-02-14 11:12 UTC, sobolevn commented on django-stubs/db/models/query.pyi
> +    def as_manager(cls) -> Manager[_T]: ...
Can you please also test it? We have a lot of bugs in QuerySet / Manager topics.
And we want to be sure it is as stable as possible.

2020-03-09 12:15 UTC, lithammer commented
Possible duplicate work in https://github.com/typeddjango/django-stubs/pull/290.

2020-03-13 17:28 UTC, silviogutierrez commented
@sobolevn : forgive me if I missed it, but is there a guide to running or developing locally? I'm trying to run tests and doing it through CI passes really takes a while. Got a lot of other fixes too that I'd love to contribute back.

I tried replicating the Travis steps but no luck.

An example here: https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#running-the-unit-tests

2020-03-13 18:04 UTC, sobolevn commented
Yes, we have a really short guide: https://github.com/typeddjango/django-stubs/blob/master/CONTRIBUTING.md

It is not perfect and I open for any feedback!

2020-10-05 07:37 UTC, RJPercival commented
Has this been abandoned?

2021-01-12 20:32 UTC, sciyoshi commented
We are waiting for this change as well as it is blocking us upgrading to Python 3.9. Is this still only waiting on tests @sobolevn?

2021-01-12 20:34 UTC, sciyoshi commented
It does look like the PR includes a test already - I'm happy to help if there's anything needed to move this forward.

2021-01-12 20:50 UTC, sobolevn commented
I would love to merge this after the CI is fixed.

2021-01-12 21:47 UTC, sciyoshi commented
After investigating a bit more - looks like this simple approach doesn't quite work and it will probably need some of the more advanced machinery from #272 or #290. I'd recommend closing this PR in favor of one of the other two unless @silviogutierrez has some further input on it.

2021-01-13 00:11 UTC, silviogutierrez commented
@sciyoshi : yea, #272 and #290 are much better solutions. Thanks all.

2021-01-13 00:11 UTC, closed without merging