Fix type errors on other models' managers when using objects = models.Manager() in Model.
typeddjango/django-stubs pull request #34
Opened 2019-02-28 22:13 UTC by syastrov

I was getting all sorts of strange type errors on other models just because I had `objects` defined on one of my models as models.Manager():
```
class Foo(models.Model):
    objects = models.Manager()

class Bar(models.Model):
    a = models.IntegerField()

Bar.objects.get(id=1).a # Type error saying no attribute 'a' is defined on 'Foo'.
```

I made the following changes:
- Fill in the type argument for that particular instance of the manager, rather than modifying the bases of the Manager type.
- Instantiate a new Instance in `determine_proper_manager_type` so the code doesn't crash under mypy-mypyc.

2019-02-28 22:25 UTC, mkurnikov requested changes

2019-02-28 22:25 UTC, mkurnikov commented on mypy_django_plugin/main.py
> +        return Instance(typ=ret.type, args=new_type_args, line=ret.line, column=ret.column)
Use `helpers.reparametrize_instance` here.

2019-03-08 07:22 UTC, syastrov commented on mypy_django_plugin/main.py
> +        return Instance(typ=ret.type, args=new_type_args, line=ret.line, column=ret.column)
👍

2019-03-08 07:23 UTC, syastrov commented
I've updated the PR to use `helpers.reparametrize_instance` and fixed a failing typecheck of a Django test.

2019-03-08 09:29 UTC, mkurnikov approved these changes

2019-03-08 09:30 UTC, merged