removed TypeVar for BaseUserManager and UserManager
typeddjango/django-stubs pull request #360
Opened 2020-04-18 17:06 UTC by kszmigiel

## Related issues

- Closes #315 

I'm not 100% sure if it'a proper way to resolve this error. If not, please give me some feedback :)

2020-04-18 18:00 UTC, sobolevn requested changes
Not all `_T` references are removed.

2021-05-26 13:53 UTC, fgarci03 commented
When will this be merged?

2021-05-26 14:01 UTC, sobolevn commented
@kszmigiel can you please rebase this PR?

2025-05-08 11:49 UTC, UnknownPlatypus commented
@sobolevn I think this MR should be closed following #1401 and discussion in #315. 

Removing the `TypeVar` could cause other issue and prevent from properly typing subclasses of `BaseUserManager`. See https://github.com/typeddjango/django-stubs/issues/315#issuecomment-1158762124

2025-05-08 11:50 UTC, closed without merging