Script for merging stubs into Django source files for testing
typeddjango/django-stubs pull request #408
Opened 2020-06-22 23:35 UTC by kszmigiel

- Closes #405

2020-06-22 23:37 UTC, kszmigiel commented
@mkurnikov @sobolevn I had not much time to sink into libcst docs yet, so here's just initial version on the script, so you can easily check my progress on this in the nearest future :)

2020-06-23 12:54 UTC, mkurnikov commented
Looks about right. Now we need to add more steps:
1. Merge all the stubs into Django sources. This will probably create lots of edge cases, at least that how it was with my experiments with `retype` from before.
2. Run mypy on top of annotated Django sources. We can start with whitelisting files to check. 
3. Community call for help, probably. Add it to CI to prevent regressions.

2020-06-25 23:35 UTC, mkurnikov requested changes

2020-06-25 23:35 UTC, mkurnikov commented on scripts/merge_stubs_into_django.py
> +stubs_dir = '../django-stubs'
Please, make paths not `..` relative, but with `Path(__file__).parent` so that script could be run from other directories too.

2020-06-25 23:43 UTC, mkurnikov commented on scripts/merge_stubs_into_django.py
> +    stubs_dict[str_path.split('/', 2)[-1].split('.')[0]] = str_path
Same thing here, use `pathlib.Path` everywhere for filesystem paths.

2020-06-25 23:59 UTC, mkurnikov commented on scripts/merge_stubs_into_django.py
> +for key in stubs_dict:
Please use `enumerate(stubs_dict)`, you're using values of the dict too

2026-07-30 09:03 UTC, UnknownPlatypus commented
Closing because stale

2026-07-30 09:03 UTC, closed without merging