updated package setup
typeddjango/django-stubs pull request #485
Opened 2020-10-11 15:43 UTC by Goldziher

Rebased version of the previous PR:

add pre-commit
improve the travis setup
cleanup and update the md files
improve the project folder structure
add stubgen scripts
update setup.py

2020-10-11 15:47 UTC, Goldziher commented
Seems that there are some problems that will require more work. Next weekend it is :).

2020-10-14 07:13 UTC, Goldziher commented
this PR is ready for review @sobolevn

2020-10-14 22:39 UTC, kszmigiel commented
@Goldziher thank you for your work!

2020-10-28 17:55 UTC, Goldziher commented
@sobolevn i rebased.

2020-10-28 18:39 UTC, sobolevn requested changes
Thanks a lot!

2020-10-28 18:39 UTC, sobolevn commented on dev-requirements.txt
> +pytest-mypy-plugins==1.6.0
It should be `1.6.1`

2020-10-28 18:39 UTC, sobolevn commented on dev-requirements.txt
> +pytest-mypy-plugins==1.6.0
Then the test failure will go away.

2020-10-29 08:32 UTC, Goldziher commented on dev-requirements.txt
> +pytest-mypy-plugins==1.6.0
done

2020-10-29 08:59 UTC, sobolevn approved these changes

2020-10-29 08:59 UTC, merged

2020-10-29 09:00 UTC, sobolevn commented
As always, @Goldziher, great work! 👍