Add stubs for remaining commands in django.core.management.commands
typeddjango/django-stubs pull request #525
Opened 2020-11-07 12:09 UTC by timmartin

This adds stubs for the remaining management commands in `django.core.management.commands`.

## Related issues

Closes #419

2020-11-07 15:42 UTC, sobolevn requested changes
Thanks!

Can you please:
1. Go through all new files and delete unused imports?
2. Remove as many `Any`s as possible

Thanks a lot for your contribution! 👍

2020-11-07 15:42 UTC, sobolevn commented on django-stubs/core/management/commands/compilemessages.pyi
> +    def compile_messages(self, locations: Any) -> None: ...
Let's fix a bit of `Any` types! I am pretty sure that `locations` cannot be `Any`, can they?

2020-11-07 15:42 UTC, sobolevn commented on django-stubs/core/management/commands/createcachetable.pyi
> +    def create_table(self, database: Any, tablename: Any, dry_run: Any) -> None: ...
Looks like `dry_run` is `bool`, `database` is `str`, etc.

2020-11-07 15:42 UTC, sobolevn commented on django-stubs/core/management/commands/dbshell.pyi
> +from typing import Any
We don't need `Any` here

2020-11-07 15:42 UTC, sobolevn commented on django-stubs/core/management/commands/flush.pyi
> +from typing import Any, Tuple
The same about `Any` here.

2020-11-08 16:29 UTC, sobolevn requested changes
Awesome! Thanks!

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/compilemessages.pyi
> +PathType = Union[str, bytes, os.PathLike]
We use `_PathType` notation when declaring our own type aliases.

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/compilemessages.pyi
> +def has_bom(fn: PathType): ...
Should return `bool`

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/compilemessages.pyi
> +def is_writable(path: PathType): ...
The same

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/squashmigrations.pyi
> +    def find_migration(self, loader: MigrationLoader, app_label: str, name: str): ...
Missing return type

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/showmigrations.pyi
> +    def show_plan(self, connection: Any, app_names: Optional[List[str]] = ...): ...
Missing return type

2020-11-08 16:29 UTC, sobolevn commented on django-stubs/core/management/commands/migrate.pyi
> +    def sync_apps(self, connection: Any, app_labels: List[str]): ...
Missing return type

2020-11-10 22:29 UTC, timmartin commented
Thanks for the review. I believe I've addressed all your comments and picked up a couple more missing annotations as I went through. There are still some missing e.g. various DB commands take `connection` as an argument, which I think is an instance of `BaseDatabaseWrapper`, but it's hard to follow since we don't yet have a declaration for the connections in `django/db/__init__.py`.

2020-11-10 22:56 UTC, sobolevn approved these changes

2020-11-10 22:56 UTC, merged

2020-11-10 22:56 UTC, sobolevn commented
Thanks for your help!