Specific return types for values and values list
typeddjango/django-stubs pull request #53
Opened 2019-03-22 22:58 UTC by syastrov

Resolves https://github.com/mkurnikov/django-stubs/issues/45

Whew... this was tougher to implement than I first imagined :)

2019-03-23 00:57 UTC, mkurnikov requested changes
Wow, this one is huge, thanks a lot! 

I'm not going to review it thoroughly, I'm going to trust your expertise and tests here. Just a few remarks. 

I'm going to run it against internal codebases tomorrow, and merge+release if everything is ok.

2019-03-23 00:57 UTC, mkurnikov commented on mypy_django_plugin/lookups.py
> +from mypy_django_plugin.transformers.fields import get_private_descriptor_type
Maybe move `get_private_descriptor_type` to `helpers` as it's used in more than one file now?

2019-03-23 00:57 UTC, mkurnikov commented on mypy_django_plugin/main.py
> +    is_nullable = is_field_nullable(ctx.type.type, field_name)
Access method with `helpers.is_field_nullable`?

2019-03-23 17:11 UTC, mkurnikov approved these changes

2019-03-23 17:14 UTC, syastrov commented
> I'm going to run it against internal codebases tomorrow, and merge+release if everything is ok.

Looking forward to hear if you catch any new errors when running on your project.

2019-03-23 17:51 UTC, syastrov commented
I ran on an internal codebase, and there were only 2 differences in the reported errors.

In the first case, compared to master, this error disappeared (was a false positive):

```
def func(arg: Iterable[Tuple[int, datetime]]) -> int:
  pass

func(MyModel.objects.annotate(some_annotation=Max('somefield')).values_list('id', 'some_annotation') # Error occurs here
```

```f.py:63: error: Argument "arg" to "func" has incompatible type "QuerySet[MyModel, Tuple[Any, ...]]"; expected "Iterable[Tuple[int, datetime]]"```

The code was erroring because for all mypy knew, the Tuple could have had any number of elements.
With this PR, mypy knows that the Tuple row type in the QuerySet has exactly 2 elements, even though it considered the type of the second Tuple element as Any (because annotations are not supported).


In the second case, the error message was more specific because the type was inferred.
master:
```f2.py:92: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "str")```

PR:
```f2.py:92: error: Incompatible types in assignment (expression has type "Optional[*str*]", variable has type "str")```

Code looks like this:
```
def f(default_token: Optional[str]):
    if default_token is not None:
        token = default_token # Inferred to be str
    else:
        token = OtherModel.objects.filter( # Error occurs here
            token__isnull=False,
            # ... other conditions here
        ).values_list("token", flat=True).first() # Inferred to be Optional[str]
    if token:
       ...
```

Although the code checks that the `token` var is not None later on (`if token`), I guess mypy doesn't like a variable that can be both Optional and non-Optional depending on the code-path.

2019-03-23 22:12 UTC, mkurnikov commented
Internal codebases gave me this
```
[CASE values_with_annotate_inside_the_expressions]
from django.db import models
from django.db.models.functions import Lower

class Publisher(models.Model):
    pass

class Book(models.Model):
    name = models.CharField(max_length=100)
    publisher = models.ForeignKey(to=Publisher, on_delete=models.CASCADE, related_name='books')

Publisher().books.values()
reveal_type(Publisher().books.values('name', lower_name=Lower('name')))
```

Revealed `TypedDict` should have `lower_name` as a key, at least as a 
```
lower_name: Any
```

2019-03-23 22:15 UTC, mkurnikov commented
This test also shows a lot of errors with stubs, fixed them in https://github.com/mkurnikov/django-stubs/pull/54

2019-03-24 20:02 UTC, syastrov commented
Thanks for the feedback. I'll look at this issue with values and kwargs.
Looks like there also may be some problems with the way the TypedDict is constructed.

2019-03-25 09:52 UTC, mkurnikov commented
Tried on internal codebase, no more errors, thanks!

2019-03-25 09:53 UTC, merged