fix: add headers to http.HttpResponseBase constructor
typeddjango/django-stubs pull request #564
Opened 2021-02-08 15:16 UTC by ChasNelson1990

Closes #563

2021-02-08 16:39 UTC, sobolevn requested changes
Thanks! 👍 

Let's also type this attribute: https://github.com/django/django/blob/master/django/http/response.py#L100

2021-02-09 14:40 UTC, ChasNelson1990 commented
@sobolevn - am I right in saying I will need to type the whole ResponseHeaders class for this?

2021-02-09 14:58 UTC, sobolevn reviewed
Thanks! 👍

2021-02-09 14:58 UTC, sobolevn commented on django-stubs/http/response.pyi
> +    headers: Union[ResponseHeaders, Dict] = ...
`.headers` are always `ResponseHeaders`

2021-02-09 15:06 UTC, ChasNelson1990 commented
Hmmm... pre-commit works fine locally (so why the GH action lint fails is confusing) but pytest fails with:
```
____________________________________ ERROR collecting django_stubs_ext/tests/test_monkeypatching.py _____________________________________
ImportError while importing test module '/home/chas/gliff/django-stubs/django_stubs_ext/tests/test_monkeypatching.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
django_stubs_ext/tests/test_monkeypatching.py:10: in <module>
    from django_stubs_ext import patch
E   ImportError: cannot import name 'patch' from 'django_stubs_ext' (unknown location)
```

2021-02-09 15:10 UTC, ChasNelson1990 commented
Do I need to install the stubs modules with `pip install -e .`?

2021-02-09 15:14 UTC, ChasNelson1990 commented
> Hmmm... pre-commit works fine locally (so why the GH action lint fails is confusing) but pytest fails with:

D'oh - local was on master

2021-02-09 15:50 UTC, sobolevn reviewed
Thanks again! I guess that this is the last iteration 👍

2021-02-09 15:50 UTC, sobolevn commented on django-stubs/http/response.pyi
> +    store: Dict = ...
`Dict[str, str]` isn't it?

2021-02-09 15:50 UTC, sobolevn commented on django-stubs/http/response.pyi
> +    def pop(self, key: str, default: Optional[str]=...) -> str: ...
`default: Optional[str] = ...`

2021-02-09 15:50 UTC, sobolevn commented on django-stubs/http/response.pyi
> +    def __init__(self, data: Dict) -> None: ...
The same here 🤔

2021-02-09 19:07 UTC, sobolevn approved these changes
Great work! 🚀

2021-02-09 19:07 UTC, merged