extend ProtectedError and RestrictedError stubs
typeddjango/django-stubs pull request #682
Opened 2021-07-30 17:43 UTC by timnyborg

types for their init methods and *_objects properties

2021-07-30 19:48 UTC, sobolevn requested changes
Thanks!

2021-07-30 19:48 UTC, sobolevn commented on django-stubs/db/models/deletion.pyi
> +    protected_objects: set[Model]
We use `typing.Set`

2021-08-03 07:09 UTC, timnyborg commented
Thanks, I've replaced with set with typing.Set

2021-08-03 08:13 UTC, sobolevn approved these changes

2021-08-03 08:13 UTC, merged

2021-08-03 08:13 UTC, sobolevn commented
Thanks!