update all path related operations to have more accurate types
typeddjango/django-stubs pull request #713
Opened 2021-09-09 23:19 UTC by terencehonles

# Description

Updates typing to better match https://github.com/django/django/blob/master/django/contrib/staticfiles/finders.py

_PathType was borrowed from https://github.com/typeddjango/django-stubs/blob/master/django-stubs/core/management/commands/compilemessages.pyi

## Related issues

2021-09-09 23:19 UTC, terencehonles commented
I accidentally created a PR against my own fork :facepalm: (I wish GitHub would stop making that so easy to not notice). This PR doesn't look like it has any merge conflicts, but I haven't looked at it since I wrote it in https://github.com/terencehonles/django-stubs/pull/1 and I am submitting this to hopefully merge it in, but also to run the CI against these changes.

2021-09-10 06:56 UTC, sobolevn requested changes
Thanks! A simple test would be very helpful!

2021-09-10 06:56 UTC, sobolevn commented on django-stubs/contrib/staticfiles/finders.pyi
> +def find(path: str, all: Literal[False] = False) -> Optional[str]: ...
We use `= ...` to define default values.

2021-09-11 19:16 UTC, terencehonles commented
> Thanks! A simple test would be very helpful!

@sobolevn done, I used https://github.com/django/django/blob/main/tests/staticfiles_tests/test_finders.py for inspiration :sweat_smile:

2021-09-11 19:41 UTC, sobolevn approved these changes
Looks great! Thanks!

2021-09-11 19:41 UTC, merged