Export Datasource, Driver from gdal
typeddjango/django-stubs pull request #797
Opened 2021-12-28 21:06 UTC by corydolphin

It looks like gdal default exports are not consistent with Django, notably missing DataSource and Driver amongst others.

https://github.com/django/django/blob/main/django/contrib/gis/gdal/__init__.py#L29

## Related issues

2021-12-29 08:03 UTC, sobolevn requested changes
Thanks! We need explicit re-export for mypy to be happy.

2021-12-29 08:03 UTC, sobolevn commented on django-stubs/contrib/gis/gdal/__init__.pyi
> +from django.contrib.gis.gdal.datasource import DataSource
```suggestion
from django.contrib.gis.gdal.datasource import DataSource as DataSource
```

2021-12-29 08:03 UTC, sobolevn commented on django-stubs/contrib/gis/gdal/__init__.pyi
> +from django.contrib.gis.gdal.driver import Driver
```suggestion
from django.contrib.gis.gdal.driver import Driver as Driver
```

2021-12-29 22:54 UTC, corydolphin commented
> Thanks! We need explicit re-export for mypy to be happy.

Thanks for the quick response. Sorry I missed that -- thank you for proposing the changes inline. Updated.

2021-12-29 23:20 UTC, sobolevn approved these changes
Please, make sure `isort` and `black` are happy 🙂 

Thank you!

2022-01-04 16:21 UTC, corydolphin commented
> Please, make sure `isort` and `black` are happy 🙂
> 
> Thank you!

Fixed! Sorry for the delay and missing that.

2022-01-04 17:39 UTC, sobolevn commented
Can you please rebase your PR?

It should be fine after https://github.com/typeddjango/django-stubs/commit/ed68fbc99f372bd6884433f44eb64748dfd4f228

2022-01-28 18:42 UTC, merged

2022-01-28 18:42 UTC, sobolevn commented
Thanks again!