Add Template class to the django template backend
typeddjango/django-stubs pull request #994
Opened 2022-06-14 03:58 UTC by SmileyChris

`django.template.backends.django` is missing a definition of its `Template` class.

2022-06-14 12:52 UTC, sobolevn requested changes
Please, take a look at:

```
/home/runner/work/django-stubs/django-stubs/django-stubs/template/backends/django.pyi:15: error: Return type "django.template.backends.django.Template" of "from_string" incompatible with return type "django.template.base.Template" in supertype "BaseEngine"
```

2022-06-20 16:27 UTC, smithdc1 reviewed
> /home/runner/work/django-stubs/django-stubs/django-stubs/template/backends/django.pyi:15: error: Return type "django.template.backends.django.Template" of "from_string" incompatible with return type "django.template.base.Template" in supertype "BaseEngine"

It looks like the `BaseEngine` has the incorrect `Template` class. 

I'm new to typing but maybe we need a protocol here that can be used for the various `Template` classes in the `backend` files.

``` python
class TemplateProto(Protocol):
    def render(
        self, 
        context: Optional[Union[Context, Dict[str, Any]]], 
        request: Optional[HttpRequest]
    ) -> Union[SafeString, TemplateDoesNotExist]: ...
```

2022-06-20 16:27 UTC, smithdc1 commented on django-stubs/template/backends/django.pyi
> +    backend: BaseEngine
Not `DjangoTemplates`?

2022-06-20 16:27 UTC, smithdc1 commented on django-stubs/template/backends/django.pyi
> +    def render(self, context: Optional[Dict[str, Any]] = None, request: Optional[_HttpRequest] = None) -> str: ...
`context` could be a `Context` too? 

https://github.com/typeddjango/django-stubs/blob/f4407155a56a50f70872d793ae365bd7d1a8691e/django-stubs/template/base.pyi#L75

2026-03-29 00:25 UTC, UnknownPlatypus commented
Superseded by #1302

2026-03-29 00:25 UTC, closed without merging